# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Maintainer: Jorge Morales <jmorales@redhat.com>
#
#

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.7.2"

VM_MEM = ENV['ORIGIN_VM_MEM'] || 8192 # Memory used for the VM
HOSTNAME = "oc-cluster-crio"

Vagrant.configure(2) do |config|

   # This vm can be created both for centos or fedora
   config.vm.box = "oc-cluster"
   config.vm.box_check_update = false
   config.vm.network "private_network", ip: "10.3.3.3"
   config.vm.synced_folder ".", "/vagrant", disabled: true
   config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
   config.vm.synced_folder "scripts", "/scripts", type: "rsync"

   config.vm.provider "virtualbox" do |vb|
      vb.memory = "#{VM_MEM}"
      vb.cpus = 2
      vb.name = "#{HOSTNAME{
   end

   config.vm.provision "shell", inline: <<-SHELL
      echo
      echo "You have a vm with latest oc-cluster"
   SHELL

end
